apiVersion: v1
kind: Service
metadata:
  name: "goa-cellar-amol"
  labels:
    app: "goa-cellar"
    chart: "goa-cellar"
    release: "test-release"
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: "goa-cellar"
    release: "test-release"
