// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "cellar": public TestHelpers
//
// Command:
// $ goagen
// --design=github.com/BlueMaverick/EPAMassignment/design
// --out=$(GOPATH)/src/github.com/BlueMaverick/EPAMassignment
// --version=v1.3.1

package test
